#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.

spring:
  application:
    name: Card_Management

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres

    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 5435

key:
  private: "C:/Users/Vlad/Desktop/Bank_Card_Management_System/src/main/resources/db/rsaKeys/private.pem"
  public:  "C:/Users/Vlad/Desktop/Bank_Card_Management_System/src/main/resources/db/rsaKeys/public.pem"
  aes: "AbCdEfGhIjKlMnOpQrStUvWxYz123456"

security:
  provider: "180.0.0.1"
  port: "5435"

